### ISSUE TITLE
Code explanation

### ISSUE THREAD

**Issue by vervas** [cloudControl/python-tornado-example-app#1]
Can you please explain me the code and especially what you do after, and what you mean, by # autodetect cpu cores and fork one process per core ?

Besides the fact that the app throws exceptions in the error log I could not find similar code on the web on using tornado and I'm not sure what is going on in your try except block.

**Comment by pst** [comment]
Re autodetect: http://www.tornadoweb.org/en/stable/tcpserver.html#tornado.tcpserver.TCPServer.start

The try except is, when the process get's killed by supervisord inside the container, the log would have a stacktrace unless you catch that KeyboardInterrupt.

**Comment by pst** [comment]
I just double checked, I can't see any exceptions in the error log.

``` bash
[pst@pst-x1 ~]$ curl https://consolebetatest.cloudcontrolled.com
Hello, world!
[pst@pst-x1 ~]$ cctrlapp consolebetatest/default log error
[Mon Jul 22 17:38:02 2013] deploy ***** Deployed 6bca7dd28425482e2b6b352ea9490bb0a289f3ee *****
```

**Comment by vervas** [comment]
OK thanks, now the core thing is clear.

Still regarding the error log, I can get errors especially if the logging is switched to info (or if someone just omits defining it to error in the Procfile).

Also I introduced the hello_world layout in it just to return proper html rendering a template instead of just returning a string.

Anyway since those changes are not on the official sample app yet I'll revert the relevant changes on the Tornado documentation and release it. You can have a look [here](https://github.com/cloudControl/documentation/commits/python_tornado/Guides/Python/Tornado.md).
